### ISSUE TITLE
after some time fhem adapter stops working

### ISSUE THREAD

**Issue by hgw77** [iobroker-community-adapters/ioBroker.fhem#37]
I use the adapter since 1 year. and I am very satisfied with that. To be honest it is one of the main reason to use IOBroker (so I can use my well working fhem installation as backend) ;-) but from the beginning I have the problem that after some time the adapter stops working. That means no new values from fhem side. Fhem is working (no known issues) and I cannot find any log entry on fhem side related to that problem. On IOBroker the same. No Log entrys that can give me a hint what happened. A restart helps. Is that a known problem?

**Comment by LausiD** [comment]
Which FHEM Adapter version?
FHEM and ioBroker  same server?

**Comment by hgw77** [comment]
FHEM Adapter Version:  1.1.1
ioBrocker Version: 3.5.10
Fhem and ioBrocker on different Servers

**Comment by LausiD** [comment]
First Update FHEM Adapter 1.2.1 from Github
Use in FHEM  dummy fhem.0.alive in room ioB_System 
on=Telnet ioBroker to FHEM OK
off=Telnet ioBroker to FHEM NOK

**Comment by hgw77** [comment]
Oh, 1.2.1 is the latest version? I didnt recogniced that, my ioBrocker shows me 1.1.1 as the latest installable version.  Found the Install from Github button in the Adpaterlist. Now it shows me 1.2.1 installed and available 1.1.1. Is that a normal behavior or is something wrong with my ioBrocker?

Thank you for your advice will try it out :-)

**Comment by Apollon77** [comment]
1.1.1 is the version flagged as "stable" and when you have selected the stable repository then you get this stable version. But 1.2.1 is also long out and should move to stable soon too (@LausiD ? :-) )
So everything is ok according to your settings

**Comment by LausiD** [comment]
@Apollon77 
First 1.2.2 in latest....if no problems of course in stable

**Comment by Apollon77** [comment]
@LausiD I merged 1.2.2 ... i will publish to npm tomorrow

**Comment by LausiD** [comment]
@Apollon77 
Thank you for your great work

**Comment by Apollon77** [comment]
Thank you, npm done, should appear in latest tomorrow afternoon

**Comment by hgw77** [comment]
very nice! but I must report that the problem still exists. After 7 days this morning the adapter stops updating values from fhem. I can see only the alive logs in the ioBrocker 

`
fhem.0 | 2019-07-08 09:23:47.680 | info | event ioBroker "fhem.0.info.Commands.sendFHEM set fhem.0.alive on-for-timer 360" > set fhem.0.alive on-for-timer 360
`

and on fhem side it shows me `fhem.0.alive` is on. But no updates from fhem side. On the other side controling switches from ioBrocker side are working.  So I guess there is something broken in reading the updates from fhem?

**Comment by LausiD** [comment]
@hgw77 
It seems like telnet connection ioB to FHEM ist OK, but FHEM to iob NOK.
Is the problem every 7 days after restart or always at the same time like monday morning or something else?
Only one idea at the moment.... second  FHEM Instanz and sync only one device from FHEM (use fhem.x.info.Configurations.onlySyncNAME)

**Comment by hgw77** [comment]
I am not sure that this happens every 7 days, I have to take a closer look but my guess it's random ;-) I will monitor it and will report it here.

About a second FHEM instance. What do you mean exactly? Or what you try to find out? It's hard to setup a second FHEM instance because all my configuration and devices (like CUL, JELINK etc.) are configured for one FHEM instance in my network ;-) Maybe there is to much load for the fhem adapter? I can see on the config side on ioBrocker a lot of events for the FHEM adapter are incoming (between ⇥60 / ↦68 and ⇥250 / ↦258) On fhem side I have some chatty devices like a Weatherstation my !MAX components or Jelink PCA301 Sensors ;-) What I can try: I can temporary reduce the devices in the ioBrocker sync-room.

By the way, in the past I tried to restart the Adapter every day but this does not help :-/ so I guess it is not related to the runtime. I using grafana to see some graphs for temperature and so on. In that graph I can see more or less the exact time when the fhem adapter stops reporting new values. But when I check the logs there is nothing bad. But I can see half an hour bevore that the Backup for ioBrocker is running (this is a complete Backup with BackItUp every day where during the process, ioBrocker is shutDown). Maybe there is a relation. I will give it a try and disable the Backups for some time.

**Comment by LausiD** [comment]
I mean: 
1. Nothing change at the first instance 
2. Define a second instance of FHEM Adapter and connect over telnet to the same FHEM Server.
Use fhem.1.info.Configurations.onlySyncNAME to sync only one device like dummy from FHEM.
3. Same problem at the same time?  

Hardware ioBroker Server?
Number of active instances? 

Good idea to disable Backups for check

**Comment by hgw77** [comment]
OK will try. "Bad thing" is that the problem appears randomly after some days so I guess I need some time for testing ;-)

At the moment I try 60min after the backup a daily restart of the fhem adapter. Maybe that helps? The FhemAdapter is also restarted during the backup process but maybe there is sometimes a edge case that causes the problem. If that does not help I will disable Backups for testing. 

Hardware ioBroker Server? it's running on a debian VM in a docker container.
Number of active instances? do you mean the Instances List in ioBrocker? There are 9 with green bubble ;-)

**Comment by LausiD** [comment]
9 days ago.........something new?

**Comment by hgw77** [comment]
sorry for delay, I was on vacation ;-) but at the moment it looks stable. I had a problem some days ago but I guess this was caused by my reconfiguration on fhem side, where I restarted the fhem multible times.

I was thinking to write a small javascript which checks for updates and if updating stops, send a message on telegram. But at the moment I check manualy  ;-)

**Comment by LausiD** [comment]
No problem :-)
What did you change?

**Comment by hgw77** [comment]
Oh I just clean up my fhem config and re aranged the devices and rooms
On iobroker side I updated my backup plugin and the admin adapter and jscontroller

So far it looks stable. I will remove the auto restart for the fhem adapter at 4 o clock and see what happens. I do a Full Backup every day at 3 o clock where iobroker is stopped so I guess the restart of the fhem adapter at 4 o clock is senseless. If the connection survices more than one week the problem is hopefully gone.

I see you released 1.3 stable but I will wait with the update until my tests are done. At the moment my adapter is Version 1.2.1

**Comment by hgw77** [comment]
I tested it the last 8 Weeks and it is much better than bevore. Nevertheless sometimes the fhem adapter stops working. There is no error on Fhem or IOBroker side reported it just stops reporting new values to IOBroker but sending commands (switch some lamp on and off) from IOBroker to Fhem works fine. I cannot say there is a pattern or something like this. One time it is working for weeks and than only one day. But mostly it is now stable :-)

Test was done with the V1.3

**Comment by LausiD** [comment]
pls check V1.4.0 from github.

**Comment by hgw77** [comment]
looks like it is now stable since 3 weeks. At the moment I restarting the adapter every 6h. I will remove that and will keep testing. Thank you very much!
